# Configuración principal para desarrollo
spring:
    profiles:
        active: dev

    datasource:
        url: jdbc:mysql://localhost:3306/bd_alimentos_fundacion_si
        username: ${DB_USERNAME:appuser}
        password: ${DB_PASSWORD:defaultpass}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: true

    security:
        user:
            name: ${ADMIN_USERNAME:admin}
            password: ${ADMIN_PASSWORD:changeThis}

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: always

logging:
    level:
        com.fundacionsi.alimentos: INFO
        org.springframework.security: WARN

server:
    port: 8080
